--liquibase formatted sql
--changeset securetag:024_add_finding_evidence

-- Add columns to store code evidence for on-demand analysis
-- code_snippet: Stores the specific vulnerable code block
-- context_snippet: Stores extended context (surrounding lines, file structure) for LLM accuracy
-- snippet_fix: Reserved for future Automated Remediation (generated by AI)

ALTER TABLE securetag.finding ADD COLUMN IF NOT EXISTS code_snippet TEXT;
ALTER TABLE securetag.finding ADD COLUMN IF NOT EXISTS context_snippet TEXT;
ALTER TABLE securetag.finding ADD COLUMN IF NOT EXISTS snippet_fix TEXT;
